<a href="https://colab.research.google.com/github/BialasDamian/data-science-bootcamp/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print(dir(np))

In [ ]:
import numpy as np
np.__version__

'1.22.4'

1D Array

In [ ]:
help(np.array)

In [6]:
x = np.array([1,3]) #TABLICA JEDNOWYMIAROWA Z ELEMENTAMI 1,3

In [7]:
print(x)            #Wyprintowanie tablicy

[1 3]


In [8]:
type(x)             #wyświetlenie typu tablicy typu nd.array


numpy.ndarray

In [9]:
#ATRYBUTY KLASY nd.array
x.ndim #Wymiary naszej tablicy


dtype('int64')

In [10]:
x.shape #Kształt 


(2,)

In [11]:
x.size #Poda liczbę elementów tablicy


2

In [12]:
x.dtype #Określa typ naszych danych

dtype('int64')

In [18]:
x = np.array([1.3,2.3,1.4])
print(x)

[1.3 2.3 1.4]


In [19]:
x.dtype

dtype('float64')

2D Array

In [24]:
x = np.array([[1,2],[-3,1]])
x

array([[ 1,  2],
       [-3,  1]])

In [25]:
x.ndim #Typ tablicy (Iluwymiarowa)

2

In [26]:
x.shape

(2, 2)

In [29]:
x = np.array([[1,2,4],[4,2,1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [30]:
x.shape

(2, 3)

3D Array

In [50]:
x = np.array(
    [[[4,3,1],
      [3,2,5]], # Przy tego typu zbiorach, oddzielenia nawiasami zamkniętymi podwójnymi, tworzy w tym przypadku dwa wiersze

      [[5,3,6],
      [2,4,7]], # ELEMENTY PO DWA WIERSZE TRZY KOLUMNY (O TYM MÓWI SHAPE)

      [[2,6,3],
       [5,3,2]]]
)
x

array([[[4, 3, 1],
        [3, 2, 5]],

       [[5, 3, 6],
        [2, 4, 7]],

       [[2, 6, 3],
        [5, 3, 2]]])

In [52]:
x.ndim #Pokazuje ilość wymiarów tablicy


3

In [51]:
x.shape # pokazuje 3 elementy, dwa wiersze i trzy kolumny

(3, 2, 3)