<a href="https://colab.research.google.com/github/BialasDamian/data-science-bootcamp/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print(dir(np))

In [ ]:
import numpy as np
np.__version__

'1.22.4'

1D Array

In [ ]:
help(np.array)

In [ ]:
x = np.array([1,3]) #TABLICA JEDNOWYMIAROWA Z ELEMENTAMI 1,3

In [ ]:
print(x)            #Wyprintowanie tablicy

[1 3]


In [ ]:
type(x)             #wyświetlenie typu tablicy typu nd.array


numpy.ndarray

In [ ]:
#ATRYBUTY KLASY nd.array
x.ndim #Wymiary naszej tablicy


dtype('int64')

In [ ]:
x.shape #Kształt 


(2,)

In [ ]:
x.size #Poda liczbę elementów tablicy


2

In [ ]:
x.dtype #Określa typ naszych danych

dtype('int64')

In [ ]:
x = np.array([1.3,2.3,1.4])
print(x)

[1.3 2.3 1.4]


In [ ]:
x.dtype

dtype('float64')

2D Array

In [ ]:
x = np.array([[1,2],[-3,1]])
x

array([[ 1,  2],
       [-3,  1]])

In [ ]:
x.ndim #Typ tablicy (Iluwymiarowa)

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x = np.array([[1,2,4],[4,2,1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [ ]:
x.shape

(2, 3)

3D Array

In [ ]:
x = np.array(
    [[[4,3,1],
      [3,2,5]], # Przy tego typu zbiorach, oddzielenia nawiasami zamkniętymi podwójnymi, tworzy w tym przypadku dwa wiersze

      [[5,3,6],
      [2,4,7]], # ELEMENTY PO DWA WIERSZE TRZY KOLUMNY (O TYM MÓWI SHAPE)

      [[2,6,3],
       [5,3,2]]]
)
x

array([[[4, 3, 1],
        [3, 2, 5]],

       [[5, 3, 6],
        [2, 4, 7]],

       [[2, 6, 3],
        [5, 3, 2]]])

In [ ]:
x.ndim #Pokazuje ilość wymiarów tablicy


3

In [ ]:
x.shape # pokazuje 3 elementy, dwa wiersze i trzy kolumny

(3, 2, 3)

In [ ]:
x.dtype

dtype('int64')

In [ ]:
A = np.array([1.0,2.3,3.3])
A.dtype

dtype('float64')

In [ ]:
A = np.array([1,2,3],dtype='float')
A.dtype

dtype('float64')

In [ ]:
A = np.array([1,2,3,],dtype='complex')
a.dtype

dtype('float64')

In [ ]:
A = np.array([1.0,2.3,3.3],dtype='int')
A.dtype

dtype('int64')

In [ ]:
A

array([1, 2, 3])

In [ ]:
A = np.array([True,False])
A.dtype

dtype('bool')

In [ ]:
A = np.array([24,120,230], dtype=np.int8) #Zmiana np zdjęcia o określonych wymiarach do 8 bitowego obrazu
A.dtype

dtype('int8')

In [ ]:
A = np.array([24,120,230],dtype=np.uint8)
A.dtype

dtype('uint8')

TWORZENIE TABLIC

In [ ]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
a.dtype

dtype('float64')

In [ ]:
np.zeros(shape=(4,10),dtype='int')


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
a.dtype

dtype('float64')

In [ ]:
np.zeros(shape=(2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(shape=(5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
np.full(shape=(3,3),fill_value=10,dtype='int')

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [ ]:
np.arange(14)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [ ]:
np.arange(start=6,stop=20)

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.arange(start=0,stop=100,step=10) #Start listy od 0 do 100, liczby co 10 krok

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.arange(start=0,stop=3,step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  , 1.05,
       1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 , 1.55, 1.6 ,
       1.65, 1.7 , 1.75, 1.8 , 1.85, 1.9 , 1.95, 2.  , 2.05, 2.1 , 2.15,
       2.2 , 2.25, 2.3 , 2.35, 2.4 , 2.45, 2.5 , 2.55, 2.6 , 2.65, 2.7 ,
       2.75, 2.8 , 2.85, 2.9 , 2.95])

In [ ]:
np.linspace(start=0,stop=1,num=11) #parametr num w np.linspace określa liczbę równo rozłożonych przedziałów liczbowych w zakresie od start do stop. num określa na ile przedziałów ma być zakres rozłożony

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
A = np.arange(15) #Tworzy listę numeryczną od 0 do 14
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape((3,5))  #Zmienia zmienną A(będącą listą, na tablicę o wymiarach 3 wierszy na 5 kolumn)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
import numpy as np 
A = np.array([2,3,6,30])
B = np.array([1,2,3,12])
print(A)
print(B)

[ 2  3  6 30]
[ 1  2  3 12]


In [7]:
A+B #DODAJE OBIE TABLICE

array([ 3,  5,  9, 42])

In [21]:
np.add(A,B) #DODAJE OBIE TABLICE

array([ 3,  5,  9, 42])

In [8]:
A-B #ODEJMUJE OBIE TABLICE

array([ 1,  1,  3, 18])

In [20]:
np.subtract(A,B) #ODEJMUJE OBIE TABLICE

array([ 1,  1,  3, 18])

In [9]:
A*B #MNOŻY OBIE TABLICE


array([  2,   6,  18, 360])

In [22]:
np.multiply(A,B) #MNOŻY OBIE TABLICE

array([  2,   6,  18, 360])

In [10]:
A/B #DZIELI OBIE TABLICE


array([2. , 1.5, 2. , 2.5])

In [23]:
np.divide(A,B) #DZIELI OBIE TABLICE

array([2. , 1.5, 2. , 2.5])

In [13]:
A**(B)

array([                 2,                  9,                216,
       531441000000000000])

In [14]:
A//B

array([2, 1, 2, 2])

In [15]:
A+3,B-1

(array([ 5,  6,  9, 33]), array([ 0,  1,  2, 11]))

In [17]:
A+3*B

array([ 5,  9, 15, 66])

In [29]:
X = np.array([[1,3],[-2,0]])
Y = np.array([[3,5],[4,-3]])
print(X)
print(Y)

[[ 1  3]
 [-2  0]]
[[ 3  5]
 [ 4 -3]]


In [30]:
X*Y

array([[ 3, 15],
       [-8,  0]])

In [31]:
np.dot(X,Y)  # np.dot ZWRACA MNOŻENIE MACIERZOWE 

array([[ 15,  -4],
       [ -6, -10]])

In [34]:
X@Y

array([[ 15,  -4],
       [ -6, -10]])

In [32]:
X.dot(Y)   # MNOŻENIE X*Y Macierzowo

array([[ 15,  -4],
       [ -6, -10]])

In [33]:
Y.dot(X)

array([[-7,  9],
       [10, 12]])

In [35]:
np.random.seed(0)

In [46]:
np.random.randn(2,3)

array([[ 1.47132196,  1.59277075, -0.25857263],
       [ 0.30833125, -1.37808347, -0.31197611]])

In [48]:
np.random.randint(10)

6

In [50]:
np.random.randint(low=1,high=100, size=3)

array([ 5,  4, 20])

In [52]:
np.random.choice([4,2,1,3]) #Losowy wybór z zakresu 

2

In [53]:
np.random.choice(['Damian','Aleksandra','Elvis'])

'Damian'

In [54]:
data = np.arange(10) #tworzy zakres od 0 do 9
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
np.random.shuffle(data) #Przetasowanie zmienia postać danych

In [58]:
data # NO I W EFEKCIE PRZETASOWAŁO KOLEJNOŚĆ DANYCH

array([1, 5, 0, 2, 9, 4, 6, 3, 8, 7])

In [59]:
np.all([2,3,1]) #np.all zwraca wartość logiczną false lub true

True

In [60]:
np.any([2,3,1]) #np.any sprawdza czy jakikolwiek obiekt jest prawdą

True

In [63]:
np.any([0,0,0]) #np.any sprawdza czy jakikolwiek obiekt jest prawdą

False

In [64]:
# bool(0) zwraca wartość false zaś jakakolwiek inna wartość zwraca wartość true

In [67]:
A = np.random.rand(5)
A

array([0.51208072, 0.97176308, 0.36384478, 0.78791575, 0.55529411])

In [70]:
np.argmax(A) # Zwraca największą wartość z tablicy "A"


1

In [71]:
c = A[np.argmax(A)] #WYCINA OWĄ WARTOŚĆ ze zbioru tablicy "A"

0.9717630761139511

In [75]:
np.argmin(A) # Zwraca najmniejszą wartość z tablicy "A"

2

In [76]:
np.argsort(A) #Sortuje elementy w tablicy "A", sortując je według indeksu "0,1,2,3,4"

array([2, 0, 4, 3, 1])

In [77]:
np.min(A) #Ukazuje minimalną wartość w zbiorze danych

0.3638447750916378

In [78]:
np.max(A) #Ukazuje maksymalną wartość w zbiorze danych

0.9717630761139511

In [79]:
np.mean(A) #Ukazuje średnią w zbiorze danych

0.6381796851100419

In [80]:
np.median(A) #Ukazuje medianę w zbiorze danych

0.5552941074669596

In [81]:
np.std(A) #Ukazuje odchylenie standardowe w zbiorze danych

0.2152809234623105

In [12]:
A = np.arange(20)
A

NameError: ignored

NameError: ignored

In [1]:
#A[idx],A[start:strip]   |||  
#A[:stop], A[start:]     ||| #wycięcie indeksu od, do na dwa sposoby
#A[10,15] Ukazuje indeks od 10 pozycji, do 15-ej pozycji