<a href="https://colab.research.google.com/github/BialasDamian/data-science-bootcamp/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print(dir(np))

In [ ]:
import numpy as np
np.__version__

'1.22.4'

1D Array

In [ ]:
help(np.array)

In [ ]:
x = np.array([1,3]) #TABLICA JEDNOWYMIAROWA Z ELEMENTAMI 1,3

In [ ]:
print(x)            #Wyprintowanie tablicy

[1 3]


In [ ]:
type(x)             #wyświetlenie typu tablicy typu nd.array


numpy.ndarray

In [ ]:
#ATRYBUTY KLASY nd.array
x.ndim #Wymiary naszej tablicy


dtype('int64')

In [ ]:
x.shape #Kształt 


(2,)

In [ ]:
x.size #Poda liczbę elementów tablicy


2

In [ ]:
x.dtype #Określa typ naszych danych

dtype('int64')

In [ ]:
x = np.array([1.3,2.3,1.4])
print(x)

[1.3 2.3 1.4]


In [ ]:
x.dtype

dtype('float64')

2D Array

In [ ]:
x = np.array([[1,2],[-3,1]])
x

array([[ 1,  2],
       [-3,  1]])

In [ ]:
x.ndim #Typ tablicy (Iluwymiarowa)

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x = np.array([[1,2,4],[4,2,1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [ ]:
x.shape

(2, 3)

3D Array

In [ ]:
x = np.array(
    [[[4,3,1],
      [3,2,5]], # Przy tego typu zbiorach, oddzielenia nawiasami zamkniętymi podwójnymi, tworzy w tym przypadku dwa wiersze

      [[5,3,6],
      [2,4,7]], # ELEMENTY PO DWA WIERSZE TRZY KOLUMNY (O TYM MÓWI SHAPE)

      [[2,6,3],
       [5,3,2]]]
)
x

array([[[4, 3, 1],
        [3, 2, 5]],

       [[5, 3, 6],
        [2, 4, 7]],

       [[2, 6, 3],
        [5, 3, 2]]])

In [ ]:
x.ndim #Pokazuje ilość wymiarów tablicy


3

In [ ]:
x.shape # pokazuje 3 elementy, dwa wiersze i trzy kolumny

(3, 2, 3)

In [ ]:
x.dtype

dtype('int64')

In [ ]:
A = np.array([1.0,2.3,3.3])
A.dtype

dtype('float64')

In [ ]:
A = np.array([1,2,3],dtype='float')
A.dtype

dtype('float64')

In [ ]:
A = np.array([1,2,3,],dtype='complex')
a.dtype

dtype('float64')

In [ ]:
A = np.array([1.0,2.3,3.3],dtype='int')
A.dtype

dtype('int64')

In [ ]:
A

array([1, 2, 3])

In [ ]:
A = np.array([True,False])
A.dtype

dtype('bool')

In [ ]:
A = np.array([24,120,230], dtype=np.int8) #Zmiana np zdjęcia o określonych wymiarach do 8 bitowego obrazu
A.dtype

dtype('int8')

In [ ]:
A = np.array([24,120,230],dtype=np.uint8)
A.dtype

dtype('uint8')

TWORZENIE TABLIC

In [ ]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
a.dtype

dtype('float64')

In [ ]:
np.zeros(shape=(4,10),dtype='int')


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
a.dtype

dtype('float64')

In [ ]:
np.zeros(shape=(2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(shape=(5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
np.full(shape=(3,3),fill_value=10,dtype='int')

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [ ]:
np.arange(14)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [ ]:
np.arange(start=6,stop=20)

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.arange(start=0,stop=100,step=10) #Start listy od 0 do 100, liczby co 10 krok

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.arange(start=0,stop=3,step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  , 1.05,
       1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 , 1.55, 1.6 ,
       1.65, 1.7 , 1.75, 1.8 , 1.85, 1.9 , 1.95, 2.  , 2.05, 2.1 , 2.15,
       2.2 , 2.25, 2.3 , 2.35, 2.4 , 2.45, 2.5 , 2.55, 2.6 , 2.65, 2.7 ,
       2.75, 2.8 , 2.85, 2.9 , 2.95])

In [ ]:
np.linspace(start=0,stop=1,num=11) #parametr num w np.linspace określa liczbę równo rozłożonych przedziałów liczbowych w zakresie od start do stop. num określa na ile przedziałów ma być zakres rozłożony

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
A = np.arange(15) #Tworzy listę numeryczną od 0 do 14
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape((3,5))  #Zmienia zmienną A(będącą listą, na tablicę o wymiarach 3 wierszy na 5 kolumn)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])