<a href="https://colab.research.google.com/github/BialasDamian/data-science-bootcamp/blob/main/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'1.22.4'

In [7]:
v1 = np.array([-1,4])
v1

array([-1,  4])

In [8]:
np.linalg.norm(v1)   #obliczenie normy wektora z algebry numpy

4.123105625617661

In [9]:
v2 = np.array([-10,20,63])
v2

array([-10,  20,  63])

In [10]:
np.linalg.norm(v2)

66.85057965343307

In [12]:
p = np.array([3,0])
q = np.array([0,4])
np.linalg.norm(p-q)

5.0

In [13]:
p = np.array([3,0,6])
q = np.array([0,4,9])
np.linalg.norm(p-q)

5.830951894845301

In [23]:
x = np.array([[5,3,6],[3,9,4]]) #MACIERZ 3x2 
y = np.array([[1,3,6],[-1,2,8],[2,6,3]]) #Macierz 3x3
print('X = \n', x,'\n')

print('Y = \n',y)

X = 
 [[5 3 6]
 [3 9 4]] 

Y = 
 [[ 1  3  6]
 [-1  2  8]
 [ 2  6  3]]


In [24]:
z = np.dot(x,y)  #Obliczanie z mnożenia macierzy 
z

array([[ 14,  57,  72],
       [  2,  51, 102]])

In [25]:
 A = np.array([[2,4],[-1,3]])
 A

array([[ 2,  4],
       [-1,  3]])

In [27]:
 A = np.array([[2,4],[-1,3]])
np.trace(A) #Określa ślad macierzy o wartości (rozwiązaniu = 5)

5

In [28]:
np.eye(5) #określa macierz typu pierwszego,drugiego itd.
np.eye(5, dtype='int') #Tworzy macierz z wartościami typu int

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [29]:
np.eye(5, dtype='float') 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
A

array([[ 2,  4],
       [-1,  3]])

In [32]:
B = np.linalg.inv(A)  #Tworzy macierz odwrotną
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [33]:
np.set_printoptions(precision=4,suppress=True)
np.dot(A,B)

array([[1., 0.],
       [0., 1.]])

In [34]:
#MACIERZ TRANSPONOWANA


array([[ 2,  4],
       [-1,  3]])

In [35]:
np.transpose(A) #Transponowana macierz jest za pomocą tej komendy

array([[ 2, -1],
       [ 4,  3]])

In [36]:
A.T #Również transponowana macierz jest za pomocą tej komendy

array([[ 2, -1],
       [ 4,  3]])

In [46]:
a = np.array([[2,4],[1,-1]])
print(a)


[[ 2  4]
 [ 1 -1]]


In [47]:
b = np.array([[10],[-1]])
print(b)

In [55]:
a_inv = np.linalg.inv(a)
x =np.dot(a_inv,b)
x

array([[1.],
       [2.]])

In [56]:
x.shape

(2, 1)