<a href="https://colab.research.google.com/github/BialasDamian/data-science-bootcamp/blob/main/03_funkcje_statystyczne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.22.4'

In [6]:
price = np.array([[12.40,12.00,11.90,12.60,1000],
              [12.50,13.00,11.70,12.20,2000],
              [12.20,13.40,12.20,13.20,1500]])
print(price)

[[  12.4   12.    11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


In [8]:
price.sum() #zsumowanie wszystkich elementów w tablicy

4649.299999999999

In [7]:
price.sum(axis=0) #Liczenie zsumowanej każdej kolumny

array([  37.1,   38.4,   35.8,   38. , 4500. ])

In [12]:
price.sum(axis=1) #Liczenie zsumowanych każdych wierszy  

array([1048.9, 2049.4, 1551. ])

In [13]:
np.sum(price)

4649.299999999999

In [14]:
np.min(price)

11.7

In [15]:
np.max(price)

2000.0

In [22]:
np.mean(price,axis = 0) #Średnia cena po kolumnach

array([  12.36666667,   12.8       ,   11.93333333,   12.66666667,
       1500.        ])

In [17]:
np.median(price)

12.5

In [23]:
np.std(price,axis = 0) #Wymiary rozrzutu / odchylenie standardowe

array([1.24721913e-01, 5.88784058e-01, 2.05480467e-01, 4.10960934e-01,
       4.08248290e+02])

In [24]:
np.var(price,axis = 0) #wariancje

array([1.55555556e-02, 3.46666667e-01, 4.22222222e-02, 1.68888889e-01,
       1.66666667e+05])